import { Inter } from 'next/font/google';
import './globals.css';
import SideBar from '@/components/partials/Sidebar';
import Jam from '@/components/partials/Jam';
import Header from '@/components/partials/Header';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
  icons: {
    icon: '/spotify_logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={`h-screen ${inter.className} overflow-x-hidden flex flex-col dark:bg-black`}>
        <Header />
        <div className="flex gap-2 flex-1">
          <SideBar />
          <main className="flex-1 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
