import { Inter } from 'next/font/google';
import './globals.css';
import SideBar from '@/components/partials/Sidebar';
import Jam from '@/components/partials/Jam';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
  icons: {
    icon: '/spotify_logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex h-screen ${inter.className}`}>
        <SideBar />
        <main className="w-4/5 h-full">
          {children}
        </main>
        <Jam />
      </body>
    </html>
  );
}
